package parsha

// Parsha is a list of parshiyos
type Parsha int32

const (
	// None a week without any parsha such as Shabbos Chol Hamoed
	None Parsha = 0 + iota
	Bereshit
	Noach
	LechLecha
	Vayera
	ChayeiSara
	Toldot
	VAYETZEI
	VAYISHLACH
	VAYESHEV
	MIKETZ
	VAYIGASH
	VAYECHI
	SHEMOS
	VAERA
	BO
	BESHALACH
	YISRO
	MISHPATIM
	TERUMAH
	TETZAVEH
	KiTisa
	VAYAKHEL
	PEKUDEI
	VAYIKRA
	TZAV
	SHMINI
	TAZRIA
	METZORA
	AchreiMot
	KEDOSHIM
	EMOR
	BEHAR
	BECHUKOSAI
	BAMIDBAR
	NASSO
	BEHAALOSCHA
	SHLACH
	KORACH
	CHUKAS
	BALAK
	PINCHAS
	MATOS
	MASEI
	DEVARIM
	VAESCHANAN
	EIKEV
	REEH
	SHOFTIM
	KiSeitzei
	KiTavo
	NITZAVIM
	VAYEILECH
	HAAZINU
	// VayakhelPekudei The double parsha of Vayakhel Peudei
	VayakhelPekudei
	// TazriaMetzora The double <em>parsha</em> of Tazria &amp; Metzora
	TazriaMetzora
	// AchreiMotKedoshim The double <em>parsha</em> of Achrei Mos Kedoshim
	AchreiMotKedoshim
	// BeharBechukosai The double <em>parsha</em>* of Behar &amp; Bechukosai
	BeharBechukosai
	// ChukatBlak The double <em>parsha</em> of Chukas Balak
	ChukatBlak
	// MatotMatei The double  * <em>parsha</em> of Matos Masei
	MatotMatei
	// NitzavimVayeilech The double <em>parsha</em> of Nitzavim Vayelech
	NitzavimVayeilech
	// SHKALIM The special parsha of Shekalim
	SHKALIM
	// ZACHOR The special <em>parsha</em> of Zachor
	ZACHOR
	// PARA The special parsha of Para
	PARA
	// HACHODESH The special parsha of Hachodesh
	HACHODESH
)

// List an array of parshiyos in the 17 possible combinations.
var List = [][]Parsha{
	{None, VAYEILECH, HAAZINU, None, Bereshit, Noach, LechLecha, Vayera, ChayeiSara, Toldot, VAYETZEI, VAYISHLACH, VAYESHEV, MIKETZ, VAYIGASH, VAYECHI, SHEMOS, VAERA, BO, BESHALACH, YISRO, MISHPATIM, TERUMAH, TETZAVEH, KiTisa, VayakhelPekudei, VAYIKRA, TZAV, None, SHMINI, TazriaMetzora, AchreiMotKedoshim, EMOR, BeharBechukosai, BAMIDBAR, NASSO, BEHAALOSCHA, SHLACH, KORACH, CHUKAS, BALAK, PINCHAS, MatotMatei, DEVARIM, VAESCHANAN, EIKEV, REEH, SHOFTIM, KiSeitzei, KiTavo, NitzavimVayeilech},
	{None, VAYEILECH, HAAZINU, None, Bereshit, Noach, LechLecha, Vayera, ChayeiSara, Toldot, VAYETZEI, VAYISHLACH, VAYESHEV, MIKETZ, VAYIGASH, VAYECHI, SHEMOS, VAERA, BO, BESHALACH, YISRO, MISHPATIM, TERUMAH, TETZAVEH, KiTisa, VayakhelPekudei, VAYIKRA, TZAV, None, SHMINI, TazriaMetzora, AchreiMotKedoshim, EMOR, BeharBechukosai, BAMIDBAR, None, NASSO, BEHAALOSCHA, SHLACH, KORACH, ChukatBlak, PINCHAS, MatotMatei, DEVARIM, VAESCHANAN, EIKEV, REEH, SHOFTIM, KiSeitzei, KiTavo, NitzavimVayeilech},
	{None, HAAZINU, None, None, Bereshit, Noach, LechLecha, Vayera, ChayeiSara, Toldot, VAYETZEI, VAYISHLACH, VAYESHEV, MIKETZ, VAYIGASH, VAYECHI, SHEMOS, VAERA, BO, BESHALACH, YISRO, MISHPATIM, TERUMAH, TETZAVEH, KiTisa, VayakhelPekudei, VAYIKRA, TZAV, None, None, SHMINI, TazriaMetzora, AchreiMotKedoshim, EMOR, BeharBechukosai, BAMIDBAR, NASSO, BEHAALOSCHA, SHLACH, KORACH, CHUKAS, BALAK, PINCHAS, MatotMatei, DEVARIM, VAESCHANAN, EIKEV, REEH, SHOFTIM, KiSeitzei, KiTavo, NITZAVIM},
	{None, HAAZINU, None, None, Bereshit, Noach, LechLecha, Vayera, ChayeiSara, Toldot, VAYETZEI, VAYISHLACH, VAYESHEV, MIKETZ, VAYIGASH, VAYECHI, SHEMOS, VAERA, BO, BESHALACH, YISRO, MISHPATIM, TERUMAH, TETZAVEH, KiTisa, VAYAKHEL, PEKUDEI, VAYIKRA, TZAV, None, SHMINI, TazriaMetzora, AchreiMotKedoshim, EMOR, BeharBechukosai, BAMIDBAR, NASSO, BEHAALOSCHA, SHLACH, KORACH, CHUKAS, BALAK, PINCHAS, MatotMatei, DEVARIM, VAESCHANAN, EIKEV, REEH, SHOFTIM, KiSeitzei, KiTavo, NITZAVIM},
	{None, None, HAAZINU, None, None, Bereshit, Noach, LechLecha, Vayera, ChayeiSara, Toldot, VAYETZEI, VAYISHLACH, VAYESHEV, MIKETZ, VAYIGASH, VAYECHI, SHEMOS, VAERA, BO, BESHALACH, YISRO, MISHPATIM, TERUMAH, TETZAVEH, KiTisa, VayakhelPekudei, VAYIKRA, TZAV, None, SHMINI, TazriaMetzora, AchreiMotKedoshim, EMOR, BeharBechukosai, BAMIDBAR, NASSO, BEHAALOSCHA, SHLACH, KORACH, CHUKAS, BALAK, PINCHAS, MatotMatei, DEVARIM, VAESCHANAN, EIKEV, REEH, SHOFTIM, KiSeitzei, KiTavo, NITZAVIM},
	{None, None, HAAZINU, None, None, Bereshit, Noach, LechLecha, Vayera, ChayeiSara, Toldot, VAYETZEI, VAYISHLACH, VAYESHEV, MIKETZ, VAYIGASH, VAYECHI, SHEMOS, VAERA, BO, BESHALACH, YISRO, MISHPATIM, TERUMAH, TETZAVEH, KiTisa, VayakhelPekudei, VAYIKRA, TZAV, None, SHMINI, TazriaMetzora, AchreiMotKedoshim, EMOR, BeharBechukosai, BAMIDBAR, NASSO, BEHAALOSCHA, SHLACH, KORACH, CHUKAS, BALAK, PINCHAS, MatotMatei, DEVARIM, VAESCHANAN, EIKEV, REEH, SHOFTIM, KiSeitzei, KiTavo, NitzavimVayeilech},
	{None, VAYEILECH, HAAZINU, None, Bereshit, Noach, LechLecha, Vayera, ChayeiSara, Toldot, VAYETZEI, VAYISHLACH, VAYESHEV, MIKETZ, VAYIGASH, VAYECHI, SHEMOS, VAERA, BO, BESHALACH, YISRO, MISHPATIM, TERUMAH, TETZAVEH, KiTisa, VAYAKHEL, PEKUDEI, VAYIKRA, TZAV, SHMINI, TAZRIA, METZORA, None, AchreiMot, KEDOSHIM, EMOR, BEHAR, BECHUKOSAI, BAMIDBAR, None, NASSO, BEHAALOSCHA, SHLACH, KORACH, ChukatBlak, PINCHAS, MatotMatei, DEVARIM, VAESCHANAN, EIKEV, REEH, SHOFTIM, KiSeitzei, KiTavo, NitzavimVayeilech},
	{None, VAYEILECH, HAAZINU, None, Bereshit, Noach, LechLecha, Vayera, ChayeiSara, Toldot, VAYETZEI, VAYISHLACH, VAYESHEV, MIKETZ, VAYIGASH, VAYECHI, SHEMOS, VAERA, BO, BESHALACH, YISRO, MISHPATIM, TERUMAH, TETZAVEH, KiTisa, VAYAKHEL, PEKUDEI, VAYIKRA, TZAV, SHMINI, TAZRIA, METZORA, None, None, AchreiMot, KEDOSHIM, EMOR, BEHAR, BECHUKOSAI, BAMIDBAR, NASSO, BEHAALOSCHA, SHLACH, KORACH, CHUKAS, BALAK, PINCHAS, MatotMatei, DEVARIM, VAESCHANAN, EIKEV, REEH, SHOFTIM, KiSeitzei, KiTavo, NITZAVIM},
	{None, HAAZINU, None, None, Bereshit, Noach, LechLecha, Vayera, ChayeiSara, Toldot, VAYETZEI, VAYISHLACH, VAYESHEV, MIKETZ, VAYIGASH, VAYECHI, SHEMOS, VAERA, BO, BESHALACH, YISRO, MISHPATIM, TERUMAH, TETZAVEH, KiTisa, VAYAKHEL, PEKUDEI, VAYIKRA, TZAV, SHMINI, TAZRIA, METZORA, AchreiMot, None, KEDOSHIM, EMOR, BEHAR, BECHUKOSAI, BAMIDBAR, NASSO, BEHAALOSCHA, SHLACH, KORACH, CHUKAS, BALAK, PINCHAS, MATOS, MASEI, DEVARIM, VAESCHANAN, EIKEV, REEH, SHOFTIM, KiSeitzei, KiTavo, NITZAVIM},
	{None, HAAZINU, None, None, Bereshit, Noach, LechLecha, Vayera, ChayeiSara, Toldot, VAYETZEI, VAYISHLACH, VAYESHEV, MIKETZ, VAYIGASH, VAYECHI, SHEMOS, VAERA, BO, BESHALACH, YISRO, MISHPATIM, TERUMAH, TETZAVEH, KiTisa, VAYAKHEL, PEKUDEI, VAYIKRA, TZAV, SHMINI, TAZRIA, METZORA, AchreiMot, None, KEDOSHIM, EMOR, BEHAR, BECHUKOSAI, BAMIDBAR, NASSO, BEHAALOSCHA, SHLACH, KORACH, CHUKAS, BALAK, PINCHAS, MATOS, MASEI, DEVARIM, VAESCHANAN, EIKEV, REEH, SHOFTIM, KiSeitzei, KiTavo, NitzavimVayeilech},
	{None, None, HAAZINU, None, None, Bereshit, Noach, LechLecha, Vayera, ChayeiSara, Toldot, VAYETZEI, VAYISHLACH, VAYESHEV, MIKETZ, VAYIGASH, VAYECHI, SHEMOS, VAERA, BO, BESHALACH, YISRO, MISHPATIM, TERUMAH, TETZAVEH, KiTisa, VAYAKHEL, PEKUDEI, VAYIKRA, TZAV, SHMINI, TAZRIA, METZORA, None, AchreiMot, KEDOSHIM, EMOR, BEHAR, BECHUKOSAI, BAMIDBAR, NASSO, BEHAALOSCHA, SHLACH, KORACH, CHUKAS, BALAK, PINCHAS, MatotMatei, DEVARIM, VAESCHANAN, EIKEV, REEH, SHOFTIM, KiSeitzei, KiTavo, NitzavimVayeilech},
	{None, None, HAAZINU, None, None, Bereshit, Noach, LechLecha, Vayera, ChayeiSara, Toldot, VAYETZEI, VAYISHLACH, VAYESHEV, MIKETZ, VAYIGASH, VAYECHI, SHEMOS, VAERA, BO, BESHALACH, YISRO, MISHPATIM, TERUMAH, TETZAVEH, KiTisa, VAYAKHEL, PEKUDEI, VAYIKRA, TZAV, SHMINI, TAZRIA, METZORA, None, AchreiMot, KEDOSHIM, EMOR, BEHAR, BECHUKOSAI, BAMIDBAR, None, NASSO, BEHAALOSCHA, SHLACH, KORACH, ChukatBlak, PINCHAS, MatotMatei, DEVARIM, VAESCHANAN, EIKEV, REEH, SHOFTIM, KiSeitzei, KiTavo, NitzavimVayeilech},
	{None, VAYEILECH, HAAZINU, None, Bereshit, Noach, LechLecha, Vayera, ChayeiSara, Toldot, VAYETZEI, VAYISHLACH, VAYESHEV, MIKETZ, VAYIGASH, VAYECHI, SHEMOS, VAERA, BO, BESHALACH, YISRO, MISHPATIM, TERUMAH, TETZAVEH, KiTisa, VayakhelPekudei, VAYIKRA, TZAV, None, SHMINI, TazriaMetzora, AchreiMotKedoshim, EMOR, BeharBechukosai, BAMIDBAR, NASSO, BEHAALOSCHA, SHLACH, KORACH, CHUKAS, BALAK, PINCHAS, MatotMatei, DEVARIM, VAESCHANAN, EIKEV, REEH, SHOFTIM, KiSeitzei, KiTavo, NitzavimVayeilech},
	{None, HAAZINU, None, None, Bereshit, Noach, LechLecha, Vayera, ChayeiSara, Toldot, VAYETZEI, VAYISHLACH, VAYESHEV, MIKETZ, VAYIGASH, VAYECHI, SHEMOS, VAERA, BO, BESHALACH, YISRO, MISHPATIM, TERUMAH, TETZAVEH, KiTisa, VayakhelPekudei, VAYIKRA, TZAV, None, SHMINI, TazriaMetzora, AchreiMotKedoshim, EMOR, BEHAR, BECHUKOSAI, BAMIDBAR, NASSO, BEHAALOSCHA, SHLACH, KORACH, CHUKAS, BALAK, PINCHAS, MatotMatei, DEVARIM, VAESCHANAN, EIKEV, REEH, SHOFTIM, KiSeitzei, KiTavo, NITZAVIM},
	{None, VAYEILECH, HAAZINU, None, Bereshit, Noach, LechLecha, Vayera, ChayeiSara, Toldot, VAYETZEI, VAYISHLACH, VAYESHEV, MIKETZ, VAYIGASH, VAYECHI, SHEMOS, VAERA, BO, BESHALACH, YISRO, MISHPATIM, TERUMAH, TETZAVEH, KiTisa, VAYAKHEL, PEKUDEI, VAYIKRA, TZAV, SHMINI, TAZRIA, METZORA, None, AchreiMot, KEDOSHIM, EMOR, BEHAR, BECHUKOSAI, BAMIDBAR, NASSO, BEHAALOSCHA, SHLACH, KORACH, CHUKAS, BALAK, PINCHAS, MatotMatei, DEVARIM, VAESCHANAN, EIKEV, REEH, SHOFTIM, KiSeitzei, KiTavo, NitzavimVayeilech},
	{None, VAYEILECH, HAAZINU, None, Bereshit, Noach, LechLecha, Vayera, ChayeiSara, Toldot, VAYETZEI, VAYISHLACH, VAYESHEV, MIKETZ, VAYIGASH, VAYECHI, SHEMOS, VAERA, BO, BESHALACH, YISRO, MISHPATIM, TERUMAH, TETZAVEH, KiTisa, VAYAKHEL, PEKUDEI, VAYIKRA, TZAV, SHMINI, TAZRIA, METZORA, None, AchreiMot, KEDOSHIM, EMOR, BEHAR, BECHUKOSAI, BAMIDBAR, NASSO, BEHAALOSCHA, SHLACH, KORACH, CHUKAS, BALAK, PINCHAS, MATOS, MASEI, DEVARIM, VAESCHANAN, EIKEV, REEH, SHOFTIM, KiSeitzei, KiTavo, NITZAVIM},
	{None, None, HAAZINU, None, None, Bereshit, Noach, LechLecha, Vayera, ChayeiSara, Toldot, VAYETZEI, VAYISHLACH, VAYESHEV, MIKETZ, VAYIGASH, VAYECHI, SHEMOS, VAERA, BO, BESHALACH, YISRO, MISHPATIM, TERUMAH, TETZAVEH, KiTisa, VAYAKHEL, PEKUDEI, VAYIKRA, TZAV, SHMINI, TAZRIA, METZORA, None, AchreiMot, KEDOSHIM, EMOR, BEHAR, BECHUKOSAI, BAMIDBAR, NASSO, BEHAALOSCHA, SHLACH, KORACH, CHUKAS, BALAK, PINCHAS, MatotMatei, DEVARIM, VAESCHANAN, EIKEV, REEH, SHOFTIM, KiSeitzei, KiTavo, NitzavimVayeilech},
}
